name "couchdb"
version "0.1.0"
maintainer "Susan Potter"
maintainer_email "me@susanpotter.net"
license "BSD3"
description "Recipes to install CouchDB"
recipe "couchdb::server", "Installation of CouchDB service."
